### ISSUE TITLE
Static Content Management

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/Management#68]
How we provide and keep up to date access to our support materials be they policies or advice or instructions or help. We appear to have evolved into a clutch of different processes and procedures.
With the FreeX1 applications we hard coded all static content(Help, Policies, Advice and Instructions). This was done by programmers writing it in html. This meant that programmers had to update the static content. With the design of FreeREG2 we took the decision to use a Content Management System (CMS)  for static content so the content providers could enter their content directly. This approach was also adopted with FreeCEN2. This worked initially but in the past year we appear to have drifted away from such an approach. We are now coding links to content that are PDFs and Google documents some on FreeUKGEN and some on Google Drive. Such links become stale and require programmer involvement to  make and change the links; thus moving away from the use of CMS and one again depending on specific people.
We need to review and establish how we intend to manage our static content.

**Comment by edickens** [comment]
Yes.  And in FreeREG1 Coordinators used to put information for researchers and acknowledgements to donors in their Progress Pages.

**Comment by richpomfret** [comment]
Process - we should not be linking directly to google docs, they should be on the FUG site.
